### PR TITLE
Sort the file list alphabetically 

### PR DESCRIPTION
**Pull request by dkam**
Title says it all really.

### CODE REVIEW

**Comment by dkam** [comment]
So, I tried my first rebase.  But I'm not sure I've done it correctly - I tried pushing a rebased branch back up into github.  This *looks* ok, but I'm not sure it's right.

**Comment by rob-murray** [comment]
Cool, thanks for all the PRs... I'm working through them when I have the time :)

**Comment by dkam** [comment]
No worries.  I’m enjoying the process.  The basic auth changes are a bit more substantial as we need to setup all the options to get the username / password stuff before Sinatra is loaded.  Basic Auth should probably be followed closely by SSL.   


> On 7 Sep 2015, at 17:54 , Robert Murray <notifications@github.com> wrote:
> 
> Cool, thanks for all the PRs... I'm working through them when I have the time :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Dan Milne d@nmilne.com
http://da.nmilne.com/  
http://booko.com.au/

**Comment by rob-murray** [comment]
Great :)

Are these all use cases you require? Just curious how you are using it...
this originated because my team just needed a basic json list of files and
download function for a mobile app prototype.

**Comment by rob-murray** [comment]
I'm gonna hold of on this one because it breaks the file download: the file is requested by the index in the array (a bit hacky I know) and so unless its sorted everywhere then these are out of sync. 

If its sorted in the first place in `FileList` then all is good.

**Pull request closed without merging**
